export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Trending } from "./Trending";
export { default as Explore } from "./Explore";
export { default as Collectors } from "./Collectors";
export { default as CreateAndSell } from "./CreateAndSell";
export { default as BidsAndNews } from "./BidsAndNews";
export { default as Sponsers } from "./Sponsers";
export { default as Footer } from "./Footer";
